apiVersion: apps/v1
kind: Deployment
metadata:
  name: results
  labels:
    app: results
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results
  template:
    metadata:
      labels:
        app: results
    spec:
      containers:
        - name: results
          image: schoolofdevops/vote-result
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: results-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: results
