apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  labels:
    app: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: schoolofdevops/vote
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: vote
